spring.application:
  name: geolocation-service

management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true

info.application:
  name: GeolocationService
  description: Geolocation Service for Real Estate Ads System
  version: 0.0.1-SNAPSHOT
---
server:
  port: 7120

cxf:
  path: /services
  servlet.init:
    service-list-path: /info
  jaxrs:
    component-scan: true
    classes-scan-packages:
      it.disim.univaq.sose.geolocation_service.config, 
      it.disim.univaq.sose.geolocation_service.webservice
  logging:
    enabled: true
    pretty-print: true
    in-mem-threshold: 1024
    limit: 10000

---
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_HOSTNAME:host.docker.internal}:${EUREKA_SERVER_PORT:8761}/eureka/
  instance:
    # Request a lease with a validity of 11 seconds. If until then the
    # lease has not been renewed, it expires and the Eureka server can evict it.
    # Default: 90s
    lease-expiration-duration-in-seconds: 11
    # The cadence of lease renewal, i.e. how often a heartbeat is sent to Eureka server.
    # In this case every 5 seconds. Use this only for development / debugging. In production use the ...
    # Default: 30s
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    statusPageUrlPath: /services/info
    healthCheckUrlPath: /actuator/health
    metadataMap:
      servletPath: ${cxf.path}
---

logging:
  feature.enabled: true
  level.org.apache.cxf: INFO