services:
  rea-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always
    volumes:
      - rea-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - rea-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  rea-phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "7071:80"
    environment:
      PMA_HOST: rea-mysql
      PMA_PORT: 3306
    networks:
      - rea-network
    depends_on:
      rea-mysql:
        condition: service_healthy

  rea-discovery-service:
    build: ./discovery-service
    image: rea-discovery-service
    ports:
      - "7002:7002"
    environment:
      SERVICE_HOSTNAME: "host.docker.internal"
      SERVICE_PORT: "7002"
    depends_on:
      rea-mysql:
        condition: service_healthy
    networks:
      - rea-network
    tty: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7002/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  rea-gateway:
    image: rea-gateway
    build: ./gateway
    ports:
      - "7100:7100"
    environment:
      EUREKA_SERVER_HOSTNAME: "host.docker.internal"
      EUREKA_SERVER_PORT: "7002"
    networks:
      - rea-network
    depends_on:
      rea-discovery-service:
        condition: service_started

  rea-account-service:
    build: ./account-service
    image: rea-account-service
    ports:
      - "7110:7110"
    environment:
      EUREKA_SERVER_HOSTNAME: "host.docker.internal"
      EUREKA_SERVER_PORT: "7002"
      MYSQL_HOST: "host.docker.internal"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7110/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      rea-mysql:
        condition: service_healthy
      rea-discovery-service:
        condition: service_healthy
    networks:
      - rea-network
    tty: true

  rea-wallet-service:
    build: ./wallet-service
    image: rea-wallet-service
    ports:
      - "7160:7160"
    environment:
      EUREKA_SERVER_HOSTNAME: "host.docker.internal"
      EUREKA_SERVER_PORT: "7002"
      MYSQL_HOST: "host.docker.internal"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7160/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      rea-mysql:
        condition: service_healthy
      rea-discovery-service:
        condition: service_healthy
    networks:
      - rea-network
    tty: true

  rea-ads-service:
    build: ./ads-service
    image: rea-ads-service
    ports:
      - "7130:7130"
    environment:
      EUREKA_SERVER_HOSTNAME: "host.docker.internal"
      EUREKA_SERVER_PORT: "7002"
      MYSQL_HOST: "host.docker.internal"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7130/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      rea-mysql:
        condition: service_healthy
      rea-discovery-service:
        condition: service_healthy
    networks:
      - rea-network
    tty: true

  rea-geolocation-service:
    build: ./geolocation-service
    image: rea-geolocation-service
    ports:
      - "7120:7120"
    environment:
      EUREKA_SERVER_HOSTNAME: "host.docker.internal"
      EUREKA_SERVER_PORT: "7002"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:7120/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      rea-discovery-service:
        condition: service_healthy
    networks:
      - rea-network
    tty: true

  rea-search-service:
    build:
        context: .
        dockerfile: search-service/Dockerfile
    image: rea-search-service
    deploy:
      replicas: 3
    ports:
      - "7140-7142:7140"
    environment:
      EUREKA_SERVER_HOSTNAME: "host.docker.internal"
      EUREKA_SERVER_PORT: "7002"
    depends_on:
      rea-discovery-service:
        condition: service_healthy
      rea-ads-service:
        condition: service_healthy
      rea-geolocation-service:
        condition: service_healthy
    networks:
      - rea-network
    tty: true

  rea-publish-service:
    build:
      context: .
      dockerfile: publish-service/Dockerfile
    image: rea-publish-service
    ports:
      - "7150:7150"
    environment:
      EUREKA_SERVER_HOSTNAME: "host.docker.internal"
      EUREKA_SERVER_PORT: "7002"
    depends_on:
      rea-discovery-service:
        condition: service_healthy
      rea-account-service:
        condition: service_healthy
      rea-ads-service:
        condition: service_healthy
      rea-wallet-service:
        condition: service_healthy
    networks:
      - rea-network
    tty: true

  rea-client:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: rea-client
    ports:
      - "80:80"
    networks:
      - rea-network
    depends_on:
      - rea-discovery-service
      - rea-gateway
      - rea-account-service
      - rea-ads-service
      - rea-geolocation-service
      - rea-search-service
      - rea-publish-service
      - rea-mysql

volumes:
  rea-mysql-data:

networks:
  rea-network:
    driver: bridge